### PR TITLE
Port to Anki 2.1

### PR DESCRIPTION
**Pull request by qsniyg**
This PR ports the plugin to Anki 2.1, without backwards compatibility for 2.0. I'm not sure how to do the latter properly, suggestions welcome.

### CODE REVIEW

**Comment by hsteve020** [comment]
does the version on this github work on 2.1?

**Comment by jakeprobst** [comment]
I was waiting for anki 2.1 to be out of beta before I merged this.

I should probably just take this .py and stick it on ankiweb though.

**Comment by hsteve020** [comment]
yes please! add a disclaimer if necessary. 

To clarify, this is functionally identical to the <2.1 anki version of 'load balancer' on "https://ankiweb.net/shared/addons/" ?

**Comment by smh020** [comment]
do you have instructions for how to manually install your 2.1 port to anki 2.1? I'm getting an error.
I made sure the zip I downloaded was the 2.1 port zip. 

image

image

image

**Comment by smh020** [comment]
getting this error.

image

**Comment by glutanimate** [comment]
Just a quick heads-up: [The scheduler has recently undergone a lot of changes](https://anki.tenderapp.com/kb/anki-ecosystem/experiment-scheduling-changes-in-anki-21) which is likely to be the cause for this error.

**Comment by hsteve020** [comment]
Now that anki 2.1 is out of beta, would it be possible to merge?

**Comment by jakeprobst** [comment]
It seems that this does not work using the latest anki from git.

**Comment by jakeprobst** [comment]
turns out its a simple fix

**Pull request merged**
